name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name (main, master, etc.)
  workflow_dispatch:    # Allows manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add host key to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
        
    - name: Deploy to Digital Ocean
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} '
          # Navigate to your project directory
          cd projects/crmkit-backend
          
          # Pull the latest code
          git pull origin main
          
          # Install dependencies (adjust based on your project)
          # For Node.js:
          # npm install
          # For Python:
          # pip install -r requirements.txt
          
          # Build your application (if needed)
          # npm run build
          
          # Restart your application (adjust based on your setup)
          # For PM2:
          # pm2 restart your-app
          # For systemd:
          # sudo systemctl restart your-service
          
          # For Docker:
          # docker-compose down
          # docker-compose up -d
          
          echo "Deployment completed!"
        '